# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false      
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install
    - name: Lint
      run: |
        pylint --load-plugins pylint_quotes wccls tests
    - name: Tests
      env:
        WCCLS_CARD_NUMBER: WCCLS_CARD_NUMBER
        WCCLS_PASSWORD: WCCLS_PASSWORD
        WCCLS_COUNT_CHECKEDOUT: 3
        WCCLS_COUNT_CHECKEDOUT_OVERDRIVE: 0
        WCCLS_COUNT_HELD: 0
        WCCLS_COUNT_HELD_OVERDRIVE: 0
        WCCLS_COUNT_SHIPPED: 0
        WCCLS_COUNT_ACTIVE: 4
        WCCLS_COUNT_INACTIVE: 6
        WCCLS_COUNT_PENDING: 0
        WCCLS_COUNT_CANCELLED: 0
        WCCLS_COUNT_UNCLAIMED: 0
        MULTCOLIB_CARD_NUMBER: MULTCOLIB_CARD_NUMBER
        MULTCOLIB_PASSWORD: MULTCOLIB_PASSWORD
        MULTCOLIB_COUNT_CHECKEDOUT: 0
        MULTCOLIB_COUNT_CHECKEDOUT_OVERDRIVE: 0
        MULTCOLIB_COUNT_HELD: 0
        MULTCOLIB_COUNT_HELD_OVERDRIVE: 0
        MULTCOLIB_COUNT_SHIPPED: 0
        MULTCOLIB_COUNT_ACTIVE: 0
        MULTCOLIB_COUNT_INACTIVE: 0
        MULTCOLIB_COUNT_PENDING: 0
        MULTCOLIB_COUNT_CANCELLED: 0
        MULTCOLIB_COUNT_UNCLAIMED: 0
        SCRUB_EMAIL: SCRUB_EMAIL
      run: |
        pytest --vcr-record=none
