# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false      
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10.0]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install
    - name: Lint
      run: |
        pylint wccls tests
    - name: Tests
      env:
        WCCLS_CARD_NUMBER: WCCLS_CARD_NUMBER
        WCCLS_PASSWORD: WCCLS_PASSWORD
        WCCLS_COUNT_CHECKOUT: 3/0
        WCCLS_COUNT_HOLDREADY: 0/0
        WCCLS_COUNT_HOLDINTRANSIT: 0/0
        WCCLS_COUNT_HOLDNOTREADY: 4/3
        WCCLS_COUNT_HOLDPAUSED: 6/0
        MULTCOLIB_CARD_NUMBER: MULTCOLIB_CARD_NUMBER
        MULTCOLIB_PASSWORD: MULTCOLIB_PASSWORD
        MULTCOLIB_COUNT_CHECKOUT: 0/0
        MULTCOLIB_COUNT_HOLDREADY: 0/0
        MULTCOLIB_COUNT_HOLDINTRANSIT: 0/0
        MULTCOLIB_COUNT_HOLDNOTREADY: 0/0
        MULTCOLIB_COUNT_HOLDPAUSED: 0/0
        SCRUB_EMAIL: SCRUB_EMAIL
      run: |
        pytest --vcr-record=none --cov=wccls
        coverage xml
    - name: Coverage
      uses: codecov/codecov-action@v2.1.0
